name: bookia1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  # hash_cached_image: ^0.0.2
  pinput: ^5.0.1
  redacted: ^1.0.13
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
          weight: 400
